name = "auctions"
type = "javascript"

account_id = "49352e8d5379bd6e7b57ad393d3bc2b9"
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2021-11-06"

[env.development]
name = "auctions-development"

[build]
command = "yarn build"
[build.upload]
format = "service-worker"
