export const deserializeFilterOptions = ({
  vocation,
  pvp,
  battleye,
  location,
  serverSet,
  skillKey,
  imbuementsSet,
  charmsSet,
  itemSet,
  questSet,
  outfitSet,
  storeOutfitSet,
  mountSet,
  storeMountSet,
  achievementSet,
  ...primitiveOptions
}: SerializedFilterOptions): FilterOptions => ({
  ...primitiveOptions,
  vocation: new Set<VocationOptions>(vocation as VocationOptions[]),
  pvp: new Set<PvpOptions>(pvp as PvpOptions[]),
  battleye: new Set<boolean>(battleye),
  location: new Set<LocationOptions>(location as LocationOptions[]),
  serverSet: new Set<string>(serverSet),
  skillKey: new Set<SkillOptions>(skillKey as SkillOptions[]),
  imbuementsSet: new Set<string>(imbuementsSet),
  charmsSet: new Set<string>(charmsSet),
  itemSet: new Set<string>(itemSet),
  questSet: new Set<string>(questSet),
  outfitSet: new Set<string>(outfitSet),
  storeOutfitSet: new Set<string>(storeOutfitSet),
  mountSet: new Set<string>(mountSet),
  storeMountSet: new Set<string>(storeMountSet),
  achievementSet: new Set<string>(achievementSet),
})

export const DEFAULT_FILTER_OPTIONS: SerializedFilterOptions = {
  nicknameFilter: '',
  vocation: [],
  pvp: [],
  battleye: [],
  location: [],
  serverSet: [],
  minLevel: 8,
  maxLevel: 2000,
  minSkill: 10,
  maxSkill: 150,
  sex: false,
  skillKey: [],
  imbuementsSet: [],
  charmsSet: [],
  itemSet: [],
  rareNick: false,
  questSet: [],
  addon: 3,
  outfitSet: [],
  storeOutfitSet: [],
  mountSet: [],
  storeMountSet: [],
  achievementSet: [],
  soulwarAvailable: false,
}
